version: "3.9"

services:
  db:
    image: postgres:15
    container_name: nanaburguer_db
    restart: always

    environment:
      POSTGRES_USER: nanaburguer
      POSTGRES_PASSWORD: nanaburguer
      POSTGRES_DB: nanaburguer_dev

    volumes:
      - postgres_data:/var/lib/postgresql/data

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U nanaburguer -d nanaburguer_dev"]
      interval: 10s
      timeout: 5s
      retries: 5

    networks:
      - nanaburguer_net

  api:
    build:
      context: ../backend/api
      dockerfile: Dockerfile.prod

    container_name: nanaburguer_api
    restart: always

    environment:
      NODE_ENV: production
      PORT: 3000
      DATABASE_URL: postgresql://nanaburguer:nanaburguer@db:5432/nanaburguer_dev?schema=public
      JWT_SECRET: super-secret-key

    ports:
      - "3000:3000"

    depends_on:
      db:
        condition: service_healthy

    networks:
      - nanaburguer_net

  frontend:
    build:
      context: ../frontend
      dockerfile: Dockerfile.prod

    container_name: nanaburguer_frontend
    restart: always

    environment:
      NODE_ENV: production
      NEXT_PUBLIC_API_URL: http://3.88.141.175:3000

    ports:
      - "80:3000"

    depends_on:
      - api

    networks:
      - nanaburguer_net

volumes:
  postgres_data:

networks:
  nanaburguer_net:
    driver: bridge
